name: Save package versions

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Folium
      uses: actions/checkout@v4

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        create-args: >-
          python=3
          --file requirements.txt
          --file requirements-dev.txt

    - name: Install folium from source
      shell: bash -l {0}
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Install folium from source
      shell: bash -l {0}
      run: |
        conda list > versions.txt

    - name: Save version.txt
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: versions.txt
        fail-on-empty: false
