name: Run Playwright Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Folium
      uses: actions/checkout@v4

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        create-args: >-
          python=3
          --file requirements.txt
          --file requirements-dev.txt

    - name: Install streamlit-folium
      shell: bash -l {0}
      run: |
        pip install streamlit-folium pytest-playwright pytest-rerunfailures

    - name: Install playwright dependencies
      shell: bash -l {0}
      run: |
        playwright install --with-deps

    - name: Install annotate-failures-plugin
      run: pip install pytest-github-actions-annotate-failures

    - name: Install folium from source
      shell: bash -l {0}
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: Test with pytest and retry flaky tests up to 3 times
      shell: bash -l {0}
      run: |
        pytest tests/playwright --browser chromium -s --reruns 3 --junit-xml=test-results.xml

    - name: Surface failing tests
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: test-results.xml
        fail-on-empty: false
